
version: '3.8'

services:
  db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: senha_root
      MYSQL_DATABASE: persons
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
